<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink([ 
                'rel' => 'shortcut icon', 
                'type' => 'image/vnd.microsoft.icon', 
                'href' => $this->basePath() . '/img/favicon.ico' 
            ]) 
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/stylemenu.css')) ?> <!-- Agregamos custom.css -->
        
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div class="wrapper">
            <!-- Sidebar -->
            <div class="sidebar">
                <button class="close-btn" onclick="toggleSidebar()">×</button>
                <ul>
                    <li><a href="<?= $this->url('home') ?>">Home</a></li>
                    <li><a href="#">Another Link</a></li>
                    <li><a href="#">More Options</a></li>
                </ul>
            </div>
            
            <!-- Main Content -->
            <div class="main-content">
                <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
                    <div class="container">
                        <button class="open-btn" onclick="toggleSidebar()">☰</button>
                        <a class="navbar-brand" href="<?= $this->url('home') ?>">
                            <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">
                            <span class="navbar-text text-light">MVC Skeleton</span>
                        </a>
                    </div>
                </nav>
                
                <div class="container">
                    <?= $this->content ?>
                    <hr>
                    <footer>
                        <p>
                            &copy; <?= date('Y') ?>
                            <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                        </p>
                    </footer>
                </div>
            </div>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js')) ?>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/script.js')) ?> <!-- Agregamos custom.js -->
    </body>
</html>
